apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: nautobot-http-sd
  name: nautobot-http-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nautobot-http-sd
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: nautobot-http-sd
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: nautobot-http-sd
          name: nautobot-http-sd
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
