{
  devices(has_primary_ip: true) {
    name
    role {
      name
    }
    location {
      name
    }
    primary_ip4 {
      address
    }
    primary_ip6 {
      address
    }
    location {
      name
    }
  }
}